### ISSUE TITLE
Docker image to launch Flask on container start

### ISSUE THREAD

**Issue by mrbende** [ashleykleynhans/llava-docker#7]
This Docker image, and the updates just pushed, is awesome! Thanks for the work here. Is it possible to create a revision of the Docker image that runs Flask on start rather than Jupyter? I'm using this as a Runpod one-click template and would like to be able to perform inference without needing to connect into the container without stopping running processes and manually launching the Flask server. I tried to fork the repo and configure this, but the image ended up in a crash loop and Flask never launched properly. 

Thanks!

**Comment by ashleykleynhans** [comment]
Flask isn't really great for this because it can't scale properly with GPU inference, Flask is basically just a demo on using an API, and you can't launch Flask ant the Web UI at the same time because they consume too much VRAM.  The average user isn't technical enough to understand how to use an API so thats why the WebUI is the default, but I can probably create a second template that has the API instead of the Gradio WebUI.

**Comment by mrbende** [comment]
Ahh I see, ok this is super helpful.

I took a stab at it with this but this is what ended up in the loop where Flask never properly starts up...
https://github.com/AttuneEngineering/llava-docker/blob/31ac8c9d6a525576635edc5f566615557dcf32e2/scripts/start.sh#L137

**Comment by mrbende** [comment]
If you can offer some pointers on launching that API instead of Gradio, I can hack at it in this fork and then submit a PR once its functional. Or just leave it as its own fork

**Comment by mrbende** [comment]
Closing this issue because I've opened two others with more specific comments, one related to this multi-GPU issue. Thanks!
